### ISSUE TITLE
Does not work in my example.

### ISSUE THREAD

**Issue by FrankenApps** [wowmaking/react-native-no-flicker-image#1]
I have tested this for my app, where I want to change a button background image on Press and I found, that the image still flickers, when I use your Component.

I built a little [demo](https://github.com/FrankenApps/AlarmButton) to show the problem.
You will have to remove 

```javascript
componentDidMount(){
  this.setState({alarm1: require("./assets/alarmon.png")});
  setTimeout(()=>{this.setState({alarm1: require("./assets/alarmoff.png")})}, 10); 
}
```
from "App.js" in order to see the problem.

**Comment by StanislavMayorov** [comment]
Hi. Thank you for the report.

**Comment by StanislavMayorov** [comment]
I couldn't reproduce flickers when image is changed first time (I had removed componentDidMount). I tested on a real android device and an emulator on mac. 
I see flickers if I change the component to Image. `NoFlickerImage` freezes and shows prev image until new image is loaded so it doesnt look good in your case with `onPressIn`, `onPressOut`. Do you want to preload images?

**Comment by FrankenApps** [comment]
I tested this again today and strangely did not notice any flickering on any of my devices anymore. I really don't know what happend, but since everything is not working as expected, I guess this can be closed...

**Comment by StanislavMayorov** [comment]
You can use hidden images `display: "none"` if you want to preload them on android. This workaround is better than `setTimeout`.
